### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ray-chew** [ray-chew/pyBELLA#12]
This issue aims to map out the strands of our discussions and provide an overview of the significant steps ahead.

[Infrastructure]
- [x] Implement diagnostic module
- [ ] Implement tests for blending and DA
- [x] Implement logger 
- [x] Implement profiler and coverage check into workflow
- [ ] Implement Christian's Baroclinic Instability test
- [ ] Add switch for IO precision
- [x] Implement tests on code integrity via pytest @benacchio 

[Documentation]
- [ ] Include write-up on the science
- [ ] Include write-up on the algorithmic implementation
- [ ] Do we want to include write-up on the discretisation? @ray-chew thinks this would be too much work.

[Refactoring]
- [x] Restructure code @ray-chew 
- [x] Move DA and blending handling strictly to the respective modules @ray-chew 
- [ ] Clean up JSON/YAML driver scripts @ray-chew 
- [ ] Clean up clumsy hydrostatic initialisation implementation

[Terrain-following coordinates (TFC)]
- [ ] Write out basic theory for TFC implementation @ray-chew 
- [ ] Decide on which implementation to go for (Prusa and Smolarkiewicz, 2003?) @ray-chew 
- [ ] Typeset Rupert's notes
- [ ] Develop new science on conservative discrete TFC formulations

**Comment by ray-chew** [comment]
As I am losing an overview in restructuring the code, this issue maps out what I find to be the most sensible approach, to be updated as I carry on making pyBELLA usable again.

- [x] RM 1. Cleanly separate all subpackages (#3, #15)
- [x] RM 2. Refactor flow solver (#8)
- [ ] RM 3. Reinstate 3D runs
- [x] RM 4. Profile and optimise flow solver
- [x] RM 5. Create test suite for initial blending (#5)
- [ ] RM 7. Create test suite for DA (#4)
- [ ] RM 8. Refactor DA subpackage 
- [x] RM 9. Restructure `sol_ens` data structure
- [ ] RM 10. Reinstate simulation restart feature

**Comment by ray-chew** [comment]
Closing this as deprecated. Creating a new roadmap with the current stand (d4d320e7377c278d806374d4a1037bbdd516fa53).
